### ISSUE TITLE
Timeouts make Protractor exit prematurely when using progress reporter

### ISSUE THREAD

**Issue by rkrisztian** [protractor-cucumber-framework/protractor-cucumber-framework#126]
If I use the `progress` formatter I get the following error:

```
[rkrisztian@localhost myproject]$ ng e2e --no-serve --no-webdriver-update
[16:20:11] I/launcher - Running 1 instances of WebDriver
[16:20:11] I/direct - Using ChromeDriver directly...
.F--...[16:21:06] E/launcher - Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
[16:21:06] E/launcher - Error: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
    at runWaitForAngularScript.then (/home/rkrisztian/myproject/node_modules/protractor/lib/browser.ts:653:19)
    at ManagedPromise.invokeCallback_ (/home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: <anonymous>
    at Timeout.pollCondition [as _onTimeout] (/home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/promise.js:2101:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From: Task: <anonymous wait>
    at scheduleWait (/home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/promise.js:2094:20)
    at ControlFlow.wait (/home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/promise.js:2408:12)
    at Driver.wait (/home/rkrisztian/myproject/node_modules/selenium-webdriver/lib/webdriver.js:943:29)
    at run (/home/rkrisztian/myproject/node_modules/protractor/lib/browser.ts:66:27)
    at ProtractorBrowser.to.(anonymous function) [as wait] (/home/rkrisztian/myproject/node_modules/protractor/lib/browser.ts:74:12)
(...)
    at World.<anonymous> (/home/rkrisztian/myproject/e2e/bdd/steps/my.steps.ts:15:23)
[16:21:06] E/launcher - Process exited with error code 199
[rkrisztian@localhost myproject]$ 
```

If I disable `progress`, I get the correct output, and the JSON reporter works too.

Using Cucumber version 3.2.1, protractor-cucumber-framework 4.2.0.

Reported originally at https://github.com/cucumber/cucumber-js/issues/1043 , then I was sent here.

**Comment by darrinholst** [comment]
Can you try setting `ignoreUncaughtExceptions: true`

https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/README.md#uncaught-exceptions

**Comment by rkrisztian** [comment]
Worked, thanks. Sorry that I didn't know about this sooner.
