### ISSUE TITLE
cucumber 4 Integration

### ISSUE THREAD

**Issue by arjun1092** [protractor-cucumber-framework/protractor-cucumber-framework#127]
Getting the following error, during execution: 

`[16:42:18] E/launcher - Cannot find module 'protractor-multiple-cucumber-html-reporter-plugin'
[16:42:18] E/launcher - Error: Cannot find module 'protractor-multiple-cucumber-html-reporter-plugin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Plugins.config.plugins.forEach (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\built\plugins.js:52:33)
    at Array.forEach (native)
    at new Plugins (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\built\plugins.js:39:28)
    at Runner.run (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\built\runner.js:317:39)
    at TaskRunner.run (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\built\taskRunner.js:110:27)
    at createNextTaskRunner (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\built\launcher.js:235:28)
    at helper.runFilenameOrFn_.then.then.then (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\built\launcher.js:260:13)
    at _fulfilled (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:604:44
    at runSingle (C:\Users\Arjun_u\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[16:42:18] E/launcher - Process exited with error code 199`

**Comment by AlexandrosD** [comment]
1. You provide no information on how the title of the issue is linked to the description.
2. You only post an exception
3. The exception is about another module that cannot be found.
