### ISSUE TITLE
Getting npm error code:105 even after installing npm install

### ISSUE THREAD

**Issue by MounikaKavadapu** [protractor-cucumber-framework/protractor-cucumber-framework#170]
npm ERR! Test failed.  See above for more details.

C:\Users\U6065633\Desktop\protractor-cucumber-typescript-master>npm test

> protractor-typescript-cucumber@4.0.0 test C:\Users\U6065633\Desktop\protractor-cucumber-typescript-master
> protractor typeScript/config/config.js

[20:36:28] E/configParser - Error code: 105
[20:36:28] E/configParser - Error message: failed loading configuration file typeScript/config/config.js
[20:36:28] E/configParser - Error: Cannot find module 'C:\Users\U6065633\Desktop\protractor-cucumber-typescript-master\typeScript\config\config.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at ConfigParser.addFileConfig (C:\Users\U6065633\Desktop\protractor-cucumber-typescript-master\node_modules\protractor\built\configParser.js:135:26)
    at Object.initFn [as init] (C:\Users\U6065633\Desktop\protractor-cucumber-typescript-master\node_modules\protractor\built\launcher.js:93:22)
    at Object.<anonymous> (C:\Users\U6065633\Desktop\protractor-cucumber-typescript-master\node_modules\protractor\built\cli.js:226:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
npm ERR! Test failed.  See above for more details.

**Comment by MounikaKavadapu** [comment]
I am able to resolve the issue by typing the tsc and then after the issue got resolved.
![tsc](https://user-images.githubusercontent.com/51371346/64626761-fe701d80-d40b-11e9-9df8-c01b105b879a.JPG)
