### ISSUE TITLE
We don't support cucumber version 6

### ISSUE THREAD

**Issue by pairmix** [protractor-cucumber-framework/protractor-cucumber-framework#171]
Hi there,
Is this project maintained again ?
I've got the following error when running my tests:

````
[16:01:39] E/launcher - Error: Error: We don't support cucumber version 6
    at Object.<anonymous> (/home/gfp/Application/current/ionic4/node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:31:11)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Function.loadCustomFormatter (/home/gfp/Application/current/ionic4/node_modules/cucumber/lib/formatter/builder.js:110:29)
    at Function.getConstructorByType (/home/gfp/Application/current/ionic4/node_modules/cucumber/lib/formatter/builder.js:77:33)
    at Function.build (/home/gfp/Application/current/ionic4/node_modules/cucumber/lib/formatter/builder.js:38:40)
    at /home/gfp/Application/current/ionic4/node_modules/cucumber/lib/cli/index.js:104:31
[16:01:39] E/launcher - Process exited with error code 100

````

**Comment by Lucas-C** [comment]
I am also affected by this error

**Comment by Lucas-C** [comment]
Done: https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/172

In the meantime, locking cucumber to an older version in my `package.json` did the trick.

**Comment by pairmix** [comment]
I prefered to remove protractor and switch to puppeteer.
