### ISSUE TITLE
"Error: 1 async operation has failed to complete within a 5s cue timeout" when using "restartBrowserBetweenTests: true"

### ISSUE THREAD

**Issue by WarioNeila86** [protractor-cucumber-framework/protractor-cucumber-framework#243]
Hi @jan-molak,

Following your advise I finally managed to reproduce the issue I mentioned [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/238#issuecomment-1032641612) with `8.3.0`.

**Steps:**
1. Clone this fork for [protractor-cucumber-framework-demo](https://github.com/WarioNeila86/protractor-cucumber-framework-demo)
2. `npm ci`
3. `npm test`

**Expected result:**
Tests are executed with no errors.

**Actual result:**
Sometimes a timeout error is thrown from `StageManager`
```
[test:execute]   Error: 1 async operation has failed to complete within a 5s cue timeout:
[test:execute]   5s 3ms - [ProtractorReporter] Invoking ProtractorRunner.afterEach...
[test:execute]       at Timeout._onTimeout (/Users/ortunom/Documents/protractor-cucumber-framework-demo/node_modules/@serenity-js/core/src/stage/StageManager.ts:43:35)
[test:execute]       at listOnTimeout (internal/timers.js:554:17)
[test:execute]       at processTimers (internal/timers.js:497:7)
```

----

- You might need to execute the tests several times, issue is not always reproducible
- I could reproduce the error using `Cucumber 5` and enabling `restartBrowserBetweenTests: true` in `protractor.conf.js`
- Also, I've found issue happens more often when using `docker-selenium` containers. You can start a standalone container executing: `docker run -d -p 4444:4444 -v /dev/shm:/dev/shm -e VNC_NO_PASSWORD=1 --name grid selenium/standalone-chrome:4.1.1-20211217`
- it also happened running standalone server locally

----

Complete log:
```
ortunom@RL3321030901 protractor-cucumber-framework-demo master% npm test

> @serenity-js/serenity-js-cucumber-protractor-template@1.0.0 test /Users/ortunom/Documents/protractor-cucumber-framework-demo
> failsafe clean test:execute test:report

[clean] 
[clean] > @serenity-js/serenity-js-cucumber-protractor-template@1.0.0 clean /Users/ortunom/Documents/protractor-cucumber-framework-demo
[clean] > rimraf target
[clean] 
[failsafe] Script 'clean' exited with code 0
[test:execute] 
[test:execute] > @serenity-js/serenity-js-cucumber-protractor-template@1.0.0 test:execute /Users/ortunom/Documents/protractor-cucumber-framework-demo
[test:execute] > protractor ./protractor.conf.js
[test:execute] 
[test:execute] [18:53:58] I/launcher - Running 1 instances of WebDriver
[test:execute] [18:53:58] I/hosted - Using the selenium server at http://localhost:4444
[test:execute] --------------------------------------------------------------------------------
[test:execute] features/super_calculator/calculations.feature:12
[test:execute] 
[test:execute] Calculations: Adding numbers
[test:execute] 
[test:execute]   Given Callie decides to use the Super Calculator
[test:execute]   When she adds 19 and 23
[test:execute]   Then she should see that the result is 42
[test:execute] 
[test:execute] ✗ Execution failed with error (8s 351ms)
[test:execute] 
[test:execute]   Error: 1 async operation has failed to complete within a 5s cue timeout:
[test:execute]   5s 3ms - [ProtractorReporter] Invoking ProtractorRunner.afterEach...
[test:execute]       at Timeout._onTimeout (/Users/ortunom/Documents/protractor-cucumber-framework-demo/node_modules/@serenity-js/core/src/stage/StageManager.ts:43:35)
[test:execute]       at listOnTimeout (internal/timers.js:554:17)
[test:execute]       at processTimers (internal/timers.js:497:7)
[test:execute] --------------------------------------------------------------------------------
[test:execute] features/super_calculator/calculations.feature:33
[test:execute] 
[test:execute] Calculations: Multiplying numbers
[test:execute] 
[test:execute]   Given Callie decides to use the Super Calculator
[test:execute]   When she multiplies -5 and -3
[test:execute]   Then she should see that the result is 15
[test:execute] 
[test:execute] ✓ Execution successful (5s 281ms)
[test:execute] --------------------------------------------------------------------------------
[test:execute] features/super_calculator/calculations.feature:34
[test:execute] 
[test:execute] Calculations: Multiplying numbers
[test:execute] 
[test:execute]   Given Callie decides to use the Super Calculator
[test:execute]   When she multiplies -5 and -3
[test:execute]   Then she should see that the result is 15
[test:execute] 
[test:execute] ✓ Execution successful (5s 58ms)
[test:execute] --------------------------------------------------------------------------------
[test:execute] features/super_calculator/calculations.feature:35
[test:execute] 
[test:execute] Calculations: Multiplying numbers
[test:execute] 
[test:execute]   Given Callie decides to use the Super Calculator
[test:execute]   When she multiplies -5 and -3
[test:execute]   Then she should see that the result is 15
[test:execute] 
[test:execute] ✓ Execution successful (4s 981ms)
[test:execute] --------------------------------------------------------------------------------
[test:execute] features/super_calculator/calculations.feature:36
[test:execute] 
[test:execute] Calculations: Multiplying numbers
[test:execute] 
[test:execute]   Given Callie decides to use the Super Calculator
[test:execute]   When she multiplies -5 and -3
[test:execute]   Then she should see that the result is 15
[test:execute] 
[test:execute] ✓ Execution successful (4s 966ms)
[test:execute] --------------------------------------------------------------------------------
[test:execute] features/super_calculator/calculations.feature:37
[test:execute] 
[test:execute] Calculations: Multiplying numbers
[test:execute] 
[test:execute]   Given Callie decides to use the Super Calculator
[test:execute]   When she multiplies -5 and -3
[test:execute]   Then she should see that the result is 15
[test:execute] 
[test:execute] ✓ Execution successful (4s 989ms)
[test:execute] --------------------------------------------------------------------------------
[test:execute] features/super_calculator/calculations.feature:38
[test:execute] 
[test:execute] Calculations: Multiplying numbers
[test:execute] 
[test:execute]   Given Callie decides to use the Super Calculator
[test:execute]   When she multiplies -5 and -3
[test:execute]   Then she should see that the result is 15
[test:execute] 
[test:execute] ✓ Execution successful (5s 35ms)
[test:execute] --------------------------------------------------------------------------------
[test:execute] features/super_calculator/calculations.feature:39
[test:execute] 
[test:execute] Calculations: Multiplying numbers
[test:execute] 
[test:execute]   Given Callie decides to use the Super Calculator
[test:execute]   When she multiplies -5 and -3
[test:execute]   Then she should see that the result is 15
[test:execute] 
[test:execute] ✓ Execution successful (4s 956ms)
[test:execute] ================================================================================
[test:execute] Execution Summary
[test:execute] 
[test:execute] Calculations: 1 broken, 7 successful, 8 total (43s 617ms)
[test:execute] 
[test:execute] Total time: 43s 617ms
[test:execute] Scenarios:  8
[test:execute] ================================================================================
[test:execute] [18:54:46] I/launcher - 0 instance(s) of WebDriver still running
[test:execute] [18:54:46] I/launcher - chrome #01 failed 1 test(s)
[test:execute] [18:54:46] I/launcher - overall: 1 failed spec(s)
[test:execute] [18:54:46] E/launcher - Process exited with error code 1
[test:execute] npm ERR! code ELIFECYCLE
[test:execute] npm ERR! errno 1
[test:execute] npm ERR! @serenity-js/serenity-js-cucumber-protractor-template@1.0.0 test:execute: `protractor ./protractor.conf.js`
[test:execute] npm ERR! Exit status 1
[test:execute] npm ERR! 
[test:execute] npm ERR! Failed at the @serenity-js/serenity-js-cucumber-protractor-template@1.0.0 test:execute script.
[test:execute] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[test:execute] 
[test:execute] npm ERR! A complete log of this run can be found in:
[test:execute] npm ERR!     /Users/ortunom/.npm/_logs/2022-02-11T17_54_46_223Z-debug.log
[failsafe] Script 'test:execute' exited with code 1
[test:report] 
[test:report] > @serenity-js/serenity-js-cucumber-protractor-template@1.0.0 test:report /Users/ortunom/Documents/protractor-cucumber-framework-demo
[test:report] > serenity-bdd run --features ./features
[test:report] 
[test:report] Spawning: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java -Dserenity.compress.filenames=true -DLOG_LEVEL=warn -Dlogback.configurationFile=/Users/ortunom/Documents/protractor-cucumber-framework-demo/node_modules/@serenity-js/serenity-bdd/resources/logback.config.xml -jar node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-2.3.31.jar --features ./features --destination target/site/serenity --source target/site/serenity --project protractor-cucumber-framework-demo
[test:report] -------------------------------
[test:report] SERENITY COMMAND LINE INTERFACE
[test:report] -------------------------------
[test:report] Loading test outcomes from target/site/serenity
[test:report] Writing aggregated report to target/site/serenity
[test:report] 
[test:report] WARNING: An illegal reflective access operation has occurred
[test:report] WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/ortunom/Documents/protractor-cucumber-framework-demo/node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-2.3.31.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
[test:report] WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
[test:report] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[test:report] WARNING: All illegal access operations will be denied in a future release
[test:report] Report generation done
[failsafe] Script 'test:report' exited with code 0
npm ERR! Test failed.  See above for more details.
```

Could you take a look, please?

Thanks!

**Comment by jan-molak** [comment]
Hi @WarioNeila86! I can't reproduce this issue locally, but I've proposed a PR that could give us more insight into what's going on on your machine - https://github.com/WarioNeila86/protractor-cucumber-framework-demo/pull/1

Let's get to the bottom of this!

**Comment by WarioNeila86** [comment]
Morning @jan-molak! I just merged your changes and reproduced the error again, please find attached new logs generated after your changes.
```
{"type":"AsyncOperationAttempted","event":{"correlationId":"ckzme1cqx000105xg86ex22u7","taskDescription":"[BrowserDetector] Detecting web browser details...","timestamp":"2022-02-14T07:41:37.353Z"}}
{"type":"SceneStarts","event":{"details":{"category":"Calculations","location":{"column":3,"line":12,"path":"features/super_calculator/calculations.feature"},"name":"Adding numbers"},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:37.352Z"}}
{"type":"FeatureNarrativeDetected","event":{"description":"In order to learn how to use Serenity/JS with Cucumber and Protractor\nAs a Curious Developer\nI'd like to see an example","sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:37.352Z"}}
{"type":"TestRunnerDetected","event":{"name":"Cucumber","sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:37.352Z"}}
{"type":"SceneTagged","event":{"sceneId":"ckzme1cqv000005xg5n4ohebv","tag":{"name":"super_calculator","type":"capability"},"timestamp":"2022-02-14T07:41:37.352Z"}}
{"type":"SceneTagged","event":{"sceneId":"ckzme1cqv000005xg5n4ohebv","tag":{"name":"Calculations","type":"feature"},"timestamp":"2022-02-14T07:41:37.352Z"}}
{"type":"SceneDescriptionDetected","event":{"description":"The [\"Super Calculator\"](https://juliemr.github.io/protractor-demo/) was developed by Julie Ralph,\nthe author of Protractor, to demonstrate what Protractor is capable of.\n\nBy the way, did you notice that with **Serenity/JS** you can use [Markdown](https://en.wikipedia.org/wiki/Markdown)\nto better describe each `Feature` and `Scenario`?","sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:37.352Z"}}
{"type":"SceneTagged","event":{"sceneId":"ckzme1cqv000005xg5n4ohebv","tag":{"name":"important","type":"tag"},"timestamp":"2022-02-14T07:41:37.352Z"}}
{"type":"SceneTagged","event":{"sceneId":"ckzme1cqv000005xg5n4ohebv","tag":{"name":"smoke","type":"tag"},"timestamp":"2022-02-14T07:41:37.353Z"}}
{"type":"SceneTagged","event":{"sceneId":"ckzme1cqv000005xg5n4ohebv","tag":{"name":"chrome 96.0.4664.110","type":"browser","browserName":"chrome","browserVersion":"96.0.4664.110"},"timestamp":"2022-02-14T07:41:37.357Z"}}
{"type":"SceneTagged","event":{"sceneId":"ckzme1cqv000005xg5n4ohebv","tag":{"name":"linux","type":"platform","platformName":"linux","platformVersion":""},"timestamp":"2022-02-14T07:41:37.357Z"}}
{"type":"AsyncOperationCompleted","event":{"correlationId":"ckzme1cqx000105xg86ex22u7","taskDescription":"[BrowserDetector] Detected web browser details","timestamp":"2022-02-14T07:41:37.357Z"}}
{"type":"TaskStarts","event":{"activityId":"ckzme1cr8000205xg0lqb8fy4","details":{"name":"Given Callie decides to use the Super Calculator"},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:37.365Z"}}
{"type":"TaskFinished","event":{"activityId":"ckzme1cr8000205xg0lqb8fy4","details":{"name":"Given Callie decides to use the Super Calculator"},"outcome":{"code":64},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:37.909Z"}}
{"type":"TaskStarts","event":{"activityId":"ckzme1d6d000305xgeqy120du","details":{"name":"When she adds 19 and 23"},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:37.909Z"}}
{"type":"TaskFinished","event":{"activityId":"ckzme1d6d000305xgeqy120du","details":{"name":"When she adds 19 and 23"},"outcome":{"code":64},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:38.274Z"}}
{"type":"TaskStarts","event":{"activityId":"ckzme1dgi000405xgck66fqeo","details":{"name":"Then she should see that the result is 42"},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:38.275Z"}}
{"type":"TaskFinished","event":{"activityId":"ckzme1dgi000405xgck66fqeo","details":{"name":"Then she should see that the result is 42"},"outcome":{"code":64},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:40.232Z"}}
{"type":"SceneFinishes","event":{"details":{"category":"Calculations","location":{"column":3,"line":12,"path":"features/super_calculator/calculations.feature"},"name":"Adding numbers"},"outcome":{"code":64},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:40.233Z"}}
{"type":"AsyncOperationAttempted","event":{"correlationId":"ckzme1eyx000505xg3y1a84t0","taskDescription":"[ProtractorReporter] Invoking ProtractorRunner.afterEach...","timestamp":"2022-02-14T07:41:40.233Z"}}
{"type":"AsyncOperationCompleted","event":{"correlationId":"ckzme1eyx000505xg3y1a84t0","taskDescription":"[ProtractorReporter] ProtractorRunner.afterEach succeeded","timestamp":"2022-02-14T07:41:45.231Z"}}
{"type":"SceneFinished","event":{"details":{"category":"Calculations","location":{"column":3,"line":12,"path":"features/super_calculator/calculations.feature"},"name":"Adding numbers"},"outcome":{"code":2,"error":"{\"name\":\"Error\",\"stack\":\"Error: function timed out, ensure the promise resolves within 5000 milliseconds\\n    at Timeout._onTimeout (/home/mario/Documents/protractor-cucumber-framework-demo/node_modules/cucumber/lib/user_code_runner.js:81:20)\\n    at listOnTimeout (node:internal/timers:557:17)\\n    at processTimers (node:internal/timers:500:7)\",\"message\":\"function timed out, ensure the promise resolves within 5000 milliseconds\"}"},"sceneId":"ckzme1cqv000005xg5n4ohebv","timestamp":"2022-02-14T07:41:45.236Z"}}
```

Full log here: [out-1644824490272.log](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/files/8058812/out-1644824490272.log).

Thanks again for taking your time helping with this!

**Comment by jan-molak** [comment]
I'm afraid it's difficult for me to suggest a solution without being able to reproduce this issue myself 🤔 

A couple of thoughts, though:
- Have you tried increasing `cueTimeout` to something silly like say 5 minutes, or maybe more? How long would the timeout need to be for all the examples to pass?
- What's the average time it takes to complete `afterEach` for the passing scenarios? Look for `AsyncOperationAttempted` / `AsyncOperationCompleted` for the passing scenarios; what's the time difference between the two? Is it close to the `cueTimeout`?
- Have you tried debugging `protractor` to see what's going on with that `afterEach` hook? If you can reproduce the issue locally, try adding a breakpoint in [Protractor Runner here](https://github.com/angular/protractor/blob/4bc80d1a459542d883ea9200e4e1f48d265d0fda/lib/runner.ts#L109) and see what's going on.
- Does the issue occur with a headless or non-headless browser? Is there any difference between the two modes?
- Have you tried running `protractor-cucumber-framework` v6 or v7 on AWS? Do both major versions pass?

Let me know if this helps?

**Comment by jan-molak** [comment]
Hey @WarioNeila86, I haven't heard from you in a couple of months so will assume that my suggestions have helped you to resolve the issue.

**Comment by WarioNeila86** [comment]
Hi @jan-molak, sorry for not coming back to this before - agree on closing the issue.

I tried some of the things you proposed back in Feb, but around the same time we started getting issues with chromedriver and in the end we had to postpone the `protractor-cucumber-framework` upgrade.

I'll let you know if we see these problems ever again. Thanks again for your help.

**Comment by jan-molak** [comment]
You're welcome, @WarioNeila86, thanks for the update!
