### ISSUE TITLE
Protractor error 105 when trying to run conf.js using Eclipse IDE.

### ISSUE THREAD

**Issue by saicharanmallampalli** [protractor-cucumber-framework/protractor-cucumber-framework#65]
Hi,
I'm new to protractor, i'm trying to run the protractor scripts through Eclipse IDE. I'm seeing the same issue.

[11:20:09] E/configParser - [SyntaxError: Unexpected token class]
[11:20:09] E/configParser - Error code: 105
[11:20:09] E/configParser - Error message: failed loading configuration file E:\Protractor\Sample-Protractor\conf.js
[11:20:09] E/configParser - SyntaxError: Unexpected token class
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:414:25)
at Object.Module._extensions..js (module.js:442:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:313:12)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at ConfigParser.addFileConfig (E:\Protractor\Sample-Protractor\node_modules\protractor\built\configParser.js:128:26)
at Object.initFn [as init] (E:\Protractor\Sample-Protractor\node_modules\protractor\built\launcher.js:97:22)
at Object. (E:\Protractor\Sample-Protractor\node_modules\protractor\built\cli.js:112:10)

Below is my conf.js and to-do.js file :

conf.js class
exports.config = {
//seleniumAddress: 'http://localhost:4444/wd/hub',
directConnect: true,
specs: ['to-do.js']
};

describe('angularjs homepage todo list', function() {
it('should add a todo', function() {
browser.get('https://angularjs.org');

element(by.model('todoList.todoText')).sendKeys('write first protractor test');
element(by.css('[value="add"]')).click();

var todoList = element.all(by.repeater('todo in todoList.todos'));
expect(todoList.count()).toEqual(3);
expect(todoList.get(2).getText()).toEqual('write first protractor test');

// You wrote your first test, cross it off the list
todoList.get(2).element(by.css('input')).click();
var completedAmount = element.all(by.css('.done-true'));
expect(completedAmount.count()).toEqual(2);
});
});

**Comment by mattbrunetti** [comment]
@saicharanmallampalli It's hard to tell, but it looks like in conf.js the text `class` is somewhere it shouldn't be, causing the syntax error. I don't think it has anything to do with Eclipse, except for the fact that Eclipse's js code intelligence and syntax highlighting is not that good in my experience. I recommend [Jetbrains Webstorm](https://www.jetbrains.com/webstorm/download/)

I don't think it has anything to do with this package (protractor-cucumber-framework) either, since from what I can tell you're not using it... Please close this issue and either move it to the protractor repo, or try out Gitter.

**Comment by AnjumMomin** [comment]
i have same problem ......
