### ISSUE TITLE
1.0.1 Dies due to Error: SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by kyleian** [protractor-cucumber-framework/protractor-cucumber-framework#74]
Hello friends,

While upgrading this module to comply with the cucumber 2.0 rc's, I'm running into an issue caused by changes introduced in 1.0.1 [at this commit](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/commit/74eeb98f7041c1510bbf7fb86a0173ef9ce5c48d#diff-168726dbe96b3ce427e7fedce31bb0bc) which are killing my test runs at the beginning of my tests:

```
Running "protractor:e2e" (protractor) task
[14:10:54] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[14:10:54] I/launcher - Running 1 instances of WebDriver
[14:10:55] E/launcher - Error: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/kyle.ian/project/node_modules/protractor/built/runner.js:340:20
    at _fulfilled (/Users/kyle.ian/project/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/kyle.ian/project/node_modules/protractor/node_modules/q/q.js:863:30)
[14:10:55] E/launcher - Process exited with error code 100
```

Unfortunately due to the constraints of my CI pipeline I'm not able to upgrade my version of node to resolve this and am stuck using node 4.6.0. Could we add a `'use strict';` to `index.js` to allow the usage of `let` in the next release, or might anyone have another option I can try out?

**Comment by kyleian** [comment]
Gonna close this as the cuke 2.0.0 es6 design won't jive with 4.6.0, paling the `use strict` change for 'let' in comparison.
