### ISSUE TITLE
Process exited with error code 199

### ISSUE THREAD

**Issue by pnakhat** [protractor-cucumber-framework/protractor-cucumber-framework#84]
HI,

I am using cuucmber js with protractor versions below
"cucumber": "^2.1.0",
"cucumber-html-reporter": "^0.4.2",
"protractor": "^5.1.0",
"protractor-cucumber-framework": "^3.1.0"

When a test fails lets day not finding an element , cucumber stops abruptly with below errors. It doesn't trigger any hooks. Happy path seems to be working fine.

Given('I am on google search page',function(next){
     browser.get("http://www.google.co.uk");
     next();
    // element(by.id('q')).sendKeys("test");
});

When(/^I search for "([^"]*)"$/, function(arg1, next) {
    // Write code here that turns the phrase above into concrete actions
    element(by.name('q')).sendKeys(arg1);
    element(by.name('q11')).submit().then(next);
});
});`

V Given I am on google search page
[14:30:44] E/launcher - No element found using locator: By(css selector, *[name="q11"])
[14:30:44] E/launcher - NoSuchElementError: No element found using locator: By(css selector, *[name="q11"])
at WebDriverError (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\error.js:27:5)
at NoSuchElementError (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\error.js:168:5)
at elementArrayFinder.getWebElements.then (C:\code\cucumber-js\node_modules\protractor\lib\element.ts:851:17)
at ManagedPromise.invokeCallback_ (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:1366:14)
at TaskQueue.execute_ (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:2970:14)
at TaskQueue.executeNext_ (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:2953:27)
at asyncRun (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:2813:27)
at C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:676:7
at process.tickCallback (internal/process/next_tick.js:109:7)Error
at ElementArrayFinder.applyAction (C:\code\cucumber-js\node_modules\protractor\lib\element.ts:482:23)
at ElementArrayFinder.(anonymous function) [as submit] (C:\code\cucumber-js\node_modules\protractor\lib\element.ts:96:21
at ElementFinder.(anonymous function) [as submit] (C:\code\cucumber-js\node_modules\protractor\lib\element.ts:873:14)
at World. (C:\code\cucumber-js\features\step_definitions\browser_steps.js:17:33)
[14:30:44] E/launcher - Process exited with error code 199
npm ERR! Test failed. See above for more details.

**Comment by darrinholst** [comment]
Please see [this](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework#uncaught-exceptions). Reopen if that doesn't solve it.

**Comment by pnakhat** [comment]
This works! Thanks!
