### ISSUE TITLE
Test execute first step and then waits till timeout when restartBrowserBetweenTests:true

### ISSUE THREAD

**Issue by Lazinka** [protractor-cucumber-framework/protractor-cucumber-framework#88]
Hello, I have problem with restarting browser between 2 scenarios. I have 2 scenarios in 1 feature file. When I put `restartBrowserBetweenTests:true` in my config file, test execute only first step from first scenario and then waits will timeout. 
```
Error: function timed out after 40000 milliseconds
         at Timeout.<anonymous> (C:\Nesto\node_modules\cucumber\lib\user_code_runner.js:91:22)
         at ontimeout (timers.js:386:14)
         at tryOnTimeout (timers.js:250:5)
         at Timer.listOnTimeout (timers.js:214:5)
```
After that, 5+ chrome browsers are spawned and first step of the second scenario is executed and again the same error with timeout is displayed.

```
14:07:36.079 INFO - Executing: [delete session: 02790592-25f6-4886-a5ed-6cec7b20350d])
14:07:37.532 INFO - Done: [delete session: 02790592-25f6-4886-a5ed-6cec7b20350d]
14:07:37.545 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
14:07:37.546 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 9275
Only local connections are allowed.
14:07:39.656 INFO - Detected dialect: OSS
14:07:39.660 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
14:07:39.677 INFO - Executing: [script wait: 11000])
14:07:39.680 INFO - Done: [script wait: 11000]
14:07:39.703 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
14:07:39.705 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 35169
Only local connections are allowed.
14:07:41.860 INFO - Detected dialect: OSS
14:07:41.869 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
14:07:41.928 INFO - Executing: [script wait: 11000])
14:07:41.931 INFO - Done: [script wait: 11000]
14:07:41.941 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
14:07:41.945 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 45762
Only local connections are allowed.
14:07:44.157 INFO - Detected dialect: OSS
14:07:44.159 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
14:07:44.168 INFO - Executing: [script wait: 11000])
14:07:44.170 INFO - Done: [script wait: 11000]
14:07:44.180 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
14:07:44.183 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 27310
Only local connections are allowed.
14:07:46.265 INFO - Detected dialect: OSS
14:07:46.269 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
14:07:46.279 INFO - Executing: [script wait: 11000])
14:07:46.286 INFO - Done: [script wait: 11000]
14:07:46.300 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
14:07:46.302 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 19504
Only local connections are allowed.
14:07:48.753 INFO - Detected dialect: OSS
14:07:48.755 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
14:07:48.822 INFO - Executing: [script wait: 11000])
14:07:48.827 INFO - Done: [script wait: 11000]
```

My `package.json`

```
{
  "name": "protractor-tests",
  "license": "ISC",
  "dependencies": {
    "protractor": "^5.1.2",
    "ts-node": "^3.1.0"
  },
  "devDependencies": {
    "@types/cucumber": "0.0.38",
    "@types/node": "^8.0.7",
    "@types/selenium-webdriver": "^3.0.4",
    "chai": "^4.0.2",
    "chai-as-promised": "^7.1.0",
    "cucumber": "^2.3.1",
    "cucumber-html-reporter": "^2.0.0",
    "mkdirp": "^0.5.1",
    "protractor-cucumber-framework": "^3.1.2",
    "selenium-webdriver": "^3.4.0",
    "typescript": "^2.2.1"
  },
  "description": "protractor",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "tsc": "tsc",
    "test": "protractor typeScript/config/config.js"
  },
  "author": "",
  "repository": ""
}
```

My `config` file
```
import { browser, Config, element, by, ExpectedConditions, protractor } from 'protractor';
import { PageObjects } from '../objects/page-objects';

var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
var expect = chai.expect;
 
export let config: Config = {

   seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
   baseUrl: 'someaddress',

    restartBrowserBetweenTests: true,

    capabilities: {
        browserName: 'chrome'
    },
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    cucumberOpts: {
        compiler: "ts:ts-node/register",
        strict: true,
        format: ['pretty'],
        require: ['../../steps/*.ts', '../../support/*.ts'],
    },
    specs: [
        '../../features/*.feature'
    ],  
    onPrepare: () => {
        browser.ignoreSynchronization = true;
        browser.manage().window().maximize();      
    } 
};
```
Example of the `steps`

```
import { browser, element, by, ExpectedConditions, protractor } from 'protractor';
import { Objects } from  '../objects/page-objects';
import { defineSupportCode } from 'cucumber';
import { config } from '../config/config'; 

var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
var expect = chai.expect;

defineSupportCode(function ({Given, When, Then }) {
   let object = new Objects();
   let ExpectedConditions = protractor.ExpectedConditions;
   var url = config.baseUrl;
   Given('Open Page and Login', function () {
       var username = 'something';
       var password = 'something';     
       browser.driver.get(url).then(function () {
               browser.wait(ExpectedConditions.elementToBeClickable(object.button));
               object.enterButton.click();
               browser.wait(ExpectedConditions.visibilityOf(object.username));
               object.username.clear();
               object.username.sendKeys(username);
               browser.wait(ExpectedConditions.visibilityOf(object.password));
               object.password.clear();
               object.password.sendKeys(password);
               browser.wait(ExpectedConditions.elementToBeClickable(object.login));
               object.loginButton.click();
     
               return expect(browser.getCurrentUrl()).to.eventually.equal(url + 'something');    
       });  
   });
```
**NOTE:** In `protractor-cucumber-framework 1.0.2` version, I was getting error `Unhandled rejection VError: a handler errored, process exiting: node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:22` after first scenario.

**Comment by darrinholst** [comment]
@Lazinka did you ever resolve this? The only thing I see that could be a problem is not returning the promise from `browser.driver.get` in the `Given`.

**Comment by Lazinka** [comment]
@darrinholst No, I didn't resolved this issue. It is still present, I changed code, but I still have issue here, it behaves as it restarts browser after every step.

**Comment by wswebcreation** [comment]
@Lazinka 

And you don't have this behaviour when you set `restartBrowserBetweenTests: false`?

**Comment by Lazinka** [comment]
@wswebcreation No, It acts normal, except I cant execute my tests in one session cause I need to restart browser because of the logging.

**Comment by wswebcreation** [comment]
Ok,

I know there are some issues in the protractor git that concern `restartBrowserBetweenTests: true`, they only concern the use of for example Jasmine, or not closing the browser at the end of all the scenario's but not the behaviour you are facing.

But just a question out of curiosity. Do you really need to close the browsers to get a clean session, or can you clean your browser state and keep it open. This can save time, but I don't know how this will work with your application, so maybe it's a dumb approach.

**Comment by Lazinka** [comment]
@wswebcreation It's not dumb :) cause I think it is only possible like this at the moment. I created Logout function at the end in After scenario function, but I am still learning and have issue there when I need to test Invalid Login, I put some if/else but till it resolve it, next scenario starts executing before first one finished.

**Comment by wswebcreation** [comment]
Sound like a promise thingy that they are not resolved in the correct way. Is there something you can share with an example project or something?

**Comment by Lazinka** [comment]
@wswebcreation I am not able to share at the moment, I will share it later.

**Comment by darrinholst** [comment]
reopen if v4.0.8 doesn't fix this
