### ISSUE TITLE
Test results error when using Scenario Outline

### ISSUE THREAD

**Issue by steelsojka** [protractor-cucumber-framework/protractor-cucumber-framework#96]
This error is throwing when a feature file contains a scenario outline:

```
Unhandled rejection TypeError: Cannot read property 'steps' of undefined
    at EventEmitter.testStepFinished (/Users/blorg/Projects/myProject/node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:86:22)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
```

The codes assumes a scenario will be found with type `Scenario` but is instead `ScenarioOutline`. 

Node: v8.3.0
protractor-cucumber-framework: 4.0.3
cucumber: 3.0.1
protractor: 5.1.1

**Comment by grishanin** [comment]
Same issue

**Comment by wswebcreation** [comment]
Can you both also post a feature-file example, just to be sure

**Comment by steelsojka** [comment]
```gherkin
@manage @permissions @adminView
Feature: Admin View Permissions

  Background:
    Given I am on the "manage" page

  Scenario Outline: View page by clicking on admin side navigation
    Given I have permission "<permission>"
    When I click on page "<page>" in the manage sidebar
    Then I should be authorized to view the "<page>" page

    Examples:
      | permission | page |
      | ADMIN_VIEW_ACCOUNTS | manage/accounts |
      | ADMIN_VIEW_BRANCHES | manage/branches |
```

**Comment by kalmykov-sergey** [comment]
Please consider https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/97

**Comment by darrinholst** [comment]
Merged. v4.0.4 has the patch.
